name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ZinerX/android_kernel_oneplus_sm8250
          kernel-dir: msm-4.19
          kernel-branch: oneplus/sm8250_u_14.0.0_op9r
          config: lito_perf_defconfig
          arch: arm64
          aosp-clang: false
          ksu: true
          ksu-version: v0.9.5
          android-version: 14
          disable-lto: true
          anykernel3: false
          vendor: true
          vendor-url: https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8250
          vendor-dir: vendor
          vendor-branch: oneplus/sm8250_u_14.0.0_op9r
          aosp-gcc: false
          other-gcc32-url: https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.9
          other-gcc64-url: https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.9
          other-clang-url: https://github.com/kdrag0n/proton-clang
          
